name = "fooetal"
uuid = "9f26f01e-d1cb-4ddb-9bf2-41c1d067cd6e"
authors = ["Nate Wagenhoffer"]
version = "1.0.0-DEV"

[deps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
